runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /backup-datastore
  login: admin
  script: datastore-admin.py
- url: /.*
  script: entrypoint.app
  secure: always

