runtime: python27
api_version: 1
threadsafe: false
application: pytantalus
version: controlled-destruction-2

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: entrypoint.app
  secure: always